services:
  mysql:
    image: mysql:latest
    restart: always
    env_file: .env
    volumes:
      - ./container_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0"]
      interval: 10s
      timeout: 5s
      retries: 3

  tg_bot:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    depends_on: 
      mysql:
        condition: service_healthy
    env_file:
      - .env
